### ISSUE TITLE
When selecting a game that's in progress, "start from beginning" starts the stream from 'live'

### ISSUE THREAD

**Issue by mrawji** [eracknaphobia/plugin.video.nhlgcl#13]
I was watching a game yesterday and wanted to start it from the beginning. When i selected that option in the UI, it started from the live position, instead of the beginning.

I can help with some testing / code, but timezones and a "one team" subscription will hamper my testing abilities.

Thanks!

**Comment by eracknaphobia** [comment]
The code that does this is a hack for sure, I noticed it's hit or miss for me as well. I rarely use this feature so it's not very high on my todo list unfortunately.

**Comment by mrawji** [comment]
Thanks. I'll poke at this as time allows.
