### ISSUE TITLE
Pause during "watch from live" isn't available

### ISSUE THREAD

**Issue by mrawji** [eracknaphobia/plugin.video.nhlgcl#14]
I was watching a live game yesterday and there's no feature to pause the live game. I think this is a feature request.

**Comment by eracknaphobia** [comment]
if inputstream adaptive is enabled you should be able to pause live stream. Is this still an issue for you?

**Comment by mrawji** [comment]
I think so. I'll poke at it some more, and confirm. Happy to take a stab at a fix if it is still a problem

**Comment by mrawji** [comment]
Ah. AdaptiveStream wasn't enabled.

For anyone else looking:
Add-ons / My Add ons / Video InputSteams...
