### ISSUE TITLE
Plugin won't start

### ISSUE THREAD

**Issue by feerlessleadr** [eracknaphobia/plugin.video.nhlgcl#17]
Hi - I went to go watch the preliminary game on right now games are no longer showing up when I enter today's game. I checked yesterday and the games were populating, but today all days are blank. I have tried to view the games on my windows laptop, android phone, & CoreELEC/Linux box, all with the same results.

Here is a log of the issue:

https://paste.ubuntu.com/p/XwsQ77W6jg/

I confirmed that the game is being televised by going through the nhl website, and I am able to watch the game through my browser.

::EDIT:: Tomorrow's games still populate, but today's games are still blank.

**Comment by notroblowe** [comment]
I'm seeing the same issue. Today's games were showing earlier, but now that the start time of the first game has passed today is showing no games. Yesterday and Tomorrow show games.

**Comment by feerlessleadr** [comment]
See here for the dev's response:
