### ISSUE TITLE
No on demand games in Kodi 19

### ISSUE THREAD

**Issue by ruppy99** [eracknaphobia/plugin.video.nhlgcl#28]
Addon only listed live and future games in Kodi 19.

Rolled back to 18 and games from past were listed again

**Comment by mrawji** [comment]
If you're feeling adventurous, checkout PR #27 ... it fixed it for me :)

**Comment by ruppy99** [comment]
Yes that works! Thanks

**Comment by mrawji** [comment]
@ruppy99 , are you having other issues since moving to v19? I am having trouble playing some of the video streams with and without adaptive streaming... switched back to v18 and everything "just worked" again...

**Comment by ruppy99** [comment]
@mrawji no issues since I installed the pull request

**Comment by eracknaphobia** [comment]
This should now be fixed in version 2021.3.8
