### ISSUE TITLE
5.15.21 - Today's Games are Missing (Live and On-Demand)

### ISSUE THREAD

**Issue by feerlessleadr** [eracknaphobia/plugin.video.nhlgcl#31]
Hi - I was able to watch the earlier game today without issue, however I just went to watch the Boston/Wash game, and there are no games listed for today (including the game I watched earlier today). 

Games from yesterday and tomorrow show up without issue but today is blank. 

This has happened on both my Android setup as well as my CoreELEC setup on my N2. 

Please see my log from my Android. 

[kodi.log](https://github.com/eracknaphobia/plugin.video.nhlgcl/files/6488439/kodi.log)

**Comment by alduder** [comment]
Same here: No playoff games are listed for today and past dates. Only games for future dates are visible.

Kodi on LibreElec. Latest NHL plugin from the Kodi repo.

**Comment by feerlessleadr** [comment]
As a temp fix, hide the scores of the games and they will show up again

**Comment by alariej** [comment]
Ooooh, good one!

**Comment by eracknaphobia** [comment]
This should now be fixed in the latest version (2021.5.17)

**Comment by feerlessleadr** [comment]
confirmed fixed - thanks!
