### ISSUE TITLE
nhl.tv now espn+?

### ISSUE THREAD

**Issue by aptdd** [eracknaphobia/plugin.video.nhlgcl#35]
I'm not sure if this is just a regional change, but espn+ is now the stream provider for nhl.tv?  Is there any way to make this app work for espn+ ?  Thanks, your plug in has been amazing!

**Comment by eracknaphobia** [comment]
This might be a good option for watching espn+ in kodi

https://www.matthuisman.nz/2021/08/espn-kodi-add-on.html

**Comment by Tanoh** [comment]
For quite a few countries in Europe we need to use ESPN Player. There is a Kodi addon for it, but it hasn't been updated in 3+ years and doesn't work. I'm in the process of thinking if I should fix it or not.

https://github.com/emilsvennesson/kodi-espnplayer

@eracknaphobia Maybe you should add this to the FAQ? Other services will not be added.
