### ISSUE TITLE
Feature request - option to completly hide the seekbar

### ISSUE THREAD

**Issue by Tanoh** [eracknaphobia/plugin.video.nhlgcl#5]
First of all, sorry if this is not the right place for this.

But I'd really, especially with the playoffs upon us soon, have an option to completly hide the seekbar (or if that's not possible fake the total time the game is). I don't know if it's possible to hide it in Kodi, I did try to google a bit for it but I couldn't find anything obvious.

Since I'm based in europe and working so I can't be up in the middle of the night to watch the games live, so I'm usually watching them the day after. Seeing that the broadcast is little over 3 hours long for example, when a normal game is just around 2 hours 45 minutes, it is quite obvious that it'll be overtime. And that will be even more obvious in the playoffs when they can play overtime for many periods.

It's annoying that NHL.tv decided to not cut out the comercial breaks like they did before in GCL but rather show the silly animation for ~2 minutes, but on the plus side they do show intermissions so that's a plus. But all in all, it's quite impossible to not see how long the broadcast is and that gives away if it'll be overtime or not.

**Comment by eracknaphobia** [comment]
http://forum.kodi.tv/showthread.php?pid=1888397

**Comment by Tanoh** [comment]
Hmm.. So it seems addons can't control it and it has to be done with a skin?

I did a simple workaround for myself, made a copy the default skin and just replaced all occurrences of ```Player.duration``` with ```...```, mostly in ```DialogSeekBar.xml```. And well, it works but it's a bit annoying to not have duration when watching non-hockey stuff. Wish it was something addons was allowed to control.

**Comment by eracknaphobia** [comment]
I'll see if there is a way from me to employ this from the add-on. I'm not too confident it will be able to but I will take a look.

**Comment by Tanoh** [comment]
Ah that would be excellent. I'd offer to help myself but I don't know enough about Kodi and kodi addons to try much more than I already did, my google-fu failed.

**Comment by eracknaphobia** [comment]
After looking at this some more I am able to set the duration, but as soon as the video stream loads my setting is overridden by the streams actual duration. Seems the skin hack is the only way to get around this for now.

**Comment by Tanoh** [comment]
Aha, too bad. Thanks for taking the time to investigate. Maybe in a future version of Kodi it'll be possible.

I'll just close this issue then.
