### ISSUE TITLE
not showing all stream options

### ISSUE THREAD

**Issue by bellt** [eracknaphobia/plugin.video.nhlgcl#53]
With nhltv not always naming the streams "home" or "away", we sometimes end up with some stream options missing from the list.
My changes, included in 17d3075, assume that there would be only one stream option that had a name different to "home" or "away", but further investigation has found that there are sometimes multiple other stream names, as shown in these examples from the website
![image](https://github.com/eracknaphobia/plugin.video.nhlgcl/assets/345478/5eb937bf-8e47-408d-ad80-99e09130f61b)
![image](https://github.com/eracknaphobia/plugin.video.nhlgcl/assets/345478/5fb8bd37-0881-4ef3-b22e-3a5ee8561387)
![image](https://github.com/eracknaphobia/plugin.video.nhlgcl/assets/345478/15a0e010-ec0c-4901-9c7e-5556ba7744b9)

Within this plugin, with the above examples the user wouldn't be presented with all of the available streams. I think we would have had a similar issue before the recent changes.

I am currently working on a fix for this, and will make a pull request when I've finished it.

**Comment by eracknaphobia** [comment]
I believe the changes that were pulled in yesterday #52 should address this. Have you tried installing version 2024.4.18 yet?
