### ISSUE TITLE
Minor stuttering problem

### ISSUE THREAD

**Issue by alduder** [eracknaphobia/plugin.video.nhlgcl#7]
Hi, thanks for this fantastic add-on. I just got myself a small Android box (Minix NEO U1), installed Kodi 17 and your add-on. It is connected over HDMI to a full HD TV, not 4K. I get 60fps and the overall stream quality is great. The only thing I noticed is that when I skip forward by pressing the arrow (right or up), the stream almost always restart with a noticeable stuttering, which doesn't go away by itself. If I pause the stream for a few seconds, the stuttering generally goes away, sometimes needing 2 or 3 pauses. Have you encountered this issue before? Let me know if you are interested to get more details. [By the way, the reason I got the Android box is because my previous setup (Ubuntu 16.04/10, Kodi 17/18 on i5 processor) became so unwatchable (because of stuttering) I had to ditch it...]

**Comment by eracknaphobia** [comment]
Seems there are still some lingering issues with video playback in Kodi 17, I've noticed on the start of my streams (fireTV Kodi 17) the video and audio are off then 5 secs later they sync up. I'm curious if you'd have the same issue using Kodi 16.

**Comment by alduder** [comment]
Thanks for the feedback. I will try to install the Kodi 16 apk on my Minix in the next days and let you know if I see this problem..

**Comment by alduder** [comment]
Hi, I did install Kodi 16 (kept all default video and playback settings) on my Android box and the stuttering is gone! I will keep this setup until they fix the problem in Kodi 17. Thanks for the hint!
